### ISSUE TITLE
Add attribute extensions support

### ISSUE THREAD

**Issue by rubenrangel** [cloudevents/sdk-php#11]
[Primer](https://github.com/cloudevents/spec/blob/v1.0.1/spec.md#extension-context-attributes) and [Spec](https://github.com/cloudevents/spec/blob/v1.0.1/spec.md#extension-context-attributes)

@jlaswell I saw https://github.com/cloudevents/sdk-php/projects/1#card-53275424 and was wondering if that ties into attribute extensions. Just trying to see what you're thinking with attribute validation in general and how that will play into this.

**Comment by jlaswell** [comment]
Wasn't thinking in terms of extensions at this point, but that's another item to capture. Only thinking of non-required context attributes as part of the event data for now. Example:

`datacontenttype` 
- Constraints:
  - OPTIONAL
  - If present, MUST adhere to the format specified in [RFC 2046](https://tools.ietf.org/html/rfc2046)

I think we need to enforce the RFC 2046 compliance at some point. some of the places this could happen are:
1. object creation
2. setting `datacontenttype`
3. getting `datacontenttype`
4. or at encoding

Think I'm leaning towards 1 and 2 to try and keep us from taking action on malformed events. 

---

Also, the projects section is a little in flux with how to best organize tasks. The [v1.0 Implementation project](https://github.com/cloudevents/sdk-php/projects/1) was a bit of a catch-all. Still thinking best way to organize.

**Comment by GrahamCampbell** [comment]
Extensions are implemented at https://github.com/cloudevents/sdk-php/pull/26.

**Comment by GrahamCampbell** [comment]
I think this issue can be closed?

**Comment by GrahamCampbell** [comment]
cc @jlaswell
