### ISSUE TITLE
JsonDeserializer can't handle all RFC3339 timestamps

### ISSUE THREAD

**Issue by anniefu** [cloudevents/sdk-php#35]
The [TimeFormatter](https://github.com/cloudevents/sdk-php/blob/master/src/Utilities/TimeFormatter.php) class causes error when deserializing CloudEvents. It does not accept all of the valid examples given in https://www.rfc-editor.org/rfc/rfc3339

The [PHP RFC3339](https://www.php.net/manual/en/class.datetimeinterface.php#datetime.constants.rfc3339) implementation should probably be used instead.

Repro:
```
<?php
require 'vendor/autoload.php';

use GuzzleHttp\Psr7\ServerRequest;
use CloudEvents\Serializers\JsonDeserializer;

$request = new ServerRequest(
   'POST',
   '',
   [],
   '{
      "specversion": "1.0",
      "type": "google.firebase.database.ref.v1.written",
      "source": "//firebasedatabase.googleapis.com/projects/_/locations/europe-west1/instances/my-project-id",
      "subject": "refs/gcf-test/xyz",
      "id": "aaaaaa-1111-bbbb-2222-cccccccccccc",
      "time": "1985-04-12T23:20:50.52Z",
      "datacontenttype": "application/cloudevents+json",
      "data": {
         "data": {
            "grandchild": "other"
         },
         "delta": {
            "grandchild": "other changed"
         }
      }
   }'
);

$event = JsonDeserializer::create()->deserializeStructured($request->getBody());
echo $event;
```

Results in:
```
PHP Fatal error:  Uncaught ValueError: CloudEvents\Utilities\TimeFormatter::decode(): Argument #1 ($time) is not a valid RFC3339 timestamp in /usr/local/google/home/anniefu/code/testing/php/vendor/cloudevents/sdk-php/src/Utilities/TimeFormatter.php:37
```

**Comment by jlaswell** [comment]
You are correct that we should update support here. I'll backlog an item to make this change to support the time-fraction portion of the spec.

**Comment by GrahamCampbell** [comment]
I've dug into the spec a bit more, and it also says that the T and Z parsing should not be case sensitive, so we possibly have another issue there, too.

**Comment by anniefu** [comment]
Perhaps just use PHP's native implementation for formatting timestamps? [PHP RFC3339](https://www.php.net/manual/en/class.datetimeinterface.php#datetime.constants.rfc3339)

**Comment by GrahamCampbell** [comment]
Unfortunately PHP's native implementation is incorrect, and they couldn't fix it for BC reasons. :trollface:

**Comment by GrahamCampbell** [comment]
I should be able to give us some kind of middleground here.

**Comment by GrahamCampbell** [comment]
https://3v4l.org/mkQKd is closer, but still not right, since the php extended constant rejects things the spec allows. The spec says you can have as many numbers as you like after the period...
