### ISSUE TITLE
Unable to use application/cloudevents+json media type

### ISSUE THREAD

**Issue by r0nder** [cloudevents/sdk-php#45]
CloudEvent specification (https://github.com/cloudevents/spec/blob/main/cloudevents/formats/json-format.md#3-envelope) suggests to use media type application/cloudevents+json when event encoded to json.
Current implementation of setter forbid to set such type because of regexp:
https://github.com/cloudevents/sdk-php/blob/main/src/V1/CloudEventTrait.php#L158

Is it possible to solve this problem?

**Comment by jlaswell** [comment]
Looks like this could be adjusted to allow for this. I'll add this to the todo list for this week, Ellie you're welcome to write the PR with tests.

**Comment by GrahamCampbell** [comment]
I think you are getting confused between the type of the "data" in the cloudevent and the type of the whole cloudevent envelope. There is no bug here IMO.

**Comment by andrii-kaidash-quarks-tech** [comment]
> I think you are getting confused between the type of the "data" in the cloudevent and the type of the whole cloudevent envelope. There is no bug here IMO.

Here we can find constraints exactly about the datacontenttype field (https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md#datacontenttype):
 format specified in [RFC 2046](https://tools.ietf.org/html/rfc2046) or Media Type examples see [IANA Media Types](http://www.iana.org/assignments/media-types/media-types.xhtml)

**Comment by r0nder** [comment]
@GrahamCampbell @

**Comment by r0nder** [comment]
@GrahamCampbell @jlaswell i would like to inquiry have we reached an understanding or probably i need additional research? Thanks

**Comment by jlaswell** [comment]
I do believe this is not a bug but there is some confusion around the usage of `application/cloudevents+json`. You can see the `UnmarshallerTest` using `application/cloudevents+json` and `application/cloudevents+xml` when passing the CloudEvent itself.

There may be a bug in the regex as mentioned, but that's not directly related to this issue. This is fair to close, but please feel free to continue the discussion if you feel this warrants more discussion.
